SECTION_START_DELIMITER = "["
SECTION_END_DELIMITER = "]"

DICT_START_DELIMITER = "{"
DICT_END_DELIMITER = "}"
DICT_KEY_SEPARATOR = ":"
DICT_ITEM_SEPARATOR = ";"

LIST_START_DELIMITER = "["
LIST_END_DELIMITER = "]"
LIST_ITEM_SEPARATOR = ","

TUPLE_START_DELIMITER = "("
TUPLE_END_DELIMITER = ")"
TUPLE_ITEM_SEPARATOR = ","
